version: 2

updates:
  # Update GitHub Actions versions weekly, on Monday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update cargo dependencies versions weekly, on Monday
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
